-- AlterTable
ALTER TABLE "cintas" ADD COLUMN     "color1" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "color2" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "color3" TEXT NOT NULL DEFAULT '#FFFFFF';
